services:
  keycloak:
    image: bitnami/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_USER=bn_keycloak
      - KEYCLOAK_DATABASE_PASSWORD=bitnami
      - KEYCLOAK_DATABASE_NAME=keycloak
    ports:
      - '8080:8080'
    depends_on:
      - postgresql
    networks:
      - api_local_net

  postgresql:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=keycloak
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - api_local_net

volumes:
  postgresql_data:
  
networks:
  api_local_net: